### ISSUE TITLE
Arrow Annotate filters out DoubleClick event before logic can fire

### ISSUE THREAD

**Issue by kubo25** [cornerstonejs/cornerstoneTools#1017]
### Prerequisites

* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

### Description

Double click events, like changing text on arrow annotation don't fire for me. I just noticed it now, but it's happening since v3.15.4.

I found that it's happening because for some reason double click fires with `event.buttons = 0`, same as in [#290](https://github.com/cornerstonejs/cornerstoneTools/issues/290). 

Before v3.15.4 in `_getNormalizedOptions` in `setToolMode.js` the `mouseButtonMask` for `0` was kept when it was in an array, however now it gets filtered out completely, which causes it not to fire.

**Comment by dannyrb** [comment]
@mikehazell recently did a lot of great work to clean up and add tests for `_getNormalizedOptions`. You can see [some of those changes at the top of this list](https://github.com/cornerstonejs/cornerstoneTools/compare/v3.15.3...master) or in PR https://github.com/cornerstonejs/cornerstoneTools/pull/903

That's probably why we're seeing this issue; however, I think this only ever worked because we were being a little sloppy with how we filtered mouseButtonMasks. If we take a look at where/how the `ArrowAnnotateTool` [hooks into updating text](https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/tools/annotation/ArrowAnnotateTool.js#L290-L296), we can see the conditions that cause it to exit.

We should probably either:

- Normalize the `doubleclick` event to say it's always triggered by a left click OR
- Remove/update these conditions in the `ArrowAnnotateTool`
    - It feels like functionality that should fire so long as the tool is in `active` or `passive` mode.

**Comment by dannyrb** [comment]
Fixed here: https://github.com/cornerstonejs/cornerstoneTools/pull/1035

Works on `doubleClick` if the arrowAnnotateTool is bound to left click. If a different tool is selected, or a arrowAnnotate is bound to a different mouse button, you won't see this relabel behavior. I think that's "okay", but understand if we want to update the tool to work when it's "passive".

LMK 🎉
