### ISSUE TITLE
How to disable a tool when another gets activated?

### ISSUE THREAD

**Issue by Ggpsv** [cornerstonejs/cornerstoneTools#1018]
### Prerequisites

* [x] Are you running the latest version?
* [ ] Are you reporting to the correct repository?
* [x] Did you perform a cursory search?

### Description

We're trying to add a new custom tool `PanZoom` which allows panning and zooming. We're aware that these controls are already available standalone and can be used simultaneously. However, the fact that they can be used simultaneously is not discoverable - hence having a tool to do so explicitly.

Here's what I have so far:

```js
/* eslint-disable */
import BaseTool from './base/BaseTool.js';
import { setToolActive, setToolDisabled } from '../store/setToolMode.js';

/**
 * @public
 * @class PanZoomWheelTool
 * @memberof Tools
 *
 * @classdesc Tool that combines Pan and ZoomWheel behavior.
 * @extends Tools.Base.BaseTool
 */

export default class PanZoomWheelTool extends BaseTool {
  constructor(props = {}) {
    const defaultProps = {
      name: 'PanZoomWheel',
      supportedInteractionTypes: ['Mouse'],
    };

    super(props, defaultProps);

    this.referencedToolNames = {
      pan: 'Pan',
      stackScroll: 'StackScrollMouseWheel',
      zoomWheel: 'ZoomMouseWheel',
    };

    this.activeCallback = this.activate.bind(this);
    this.disabledCallback = this.deactivate.bind(this);
  }

  activate() {
    setToolDisabled(this.referencedToolNames.stackScroll);
    setToolActive(this.referencedToolNames.pan, { mouseButtonMask: 1 });
    setToolActive(this.referencedToolNames.zoomWheel, { mouseButtonMask: 4 });
  }

  deactivate() {
    setToolActive(this.referencedToolNames.stackScroll);
    setToolDisabled(this.referencedToolNames.pan);
    setToolDisabled(this.referencedToolNames.zoomWheel);
  }
}
```

The tool activates and the panning and zoom work as expected. However, I can't seem to get `deactivate` fired in `disabledCallback`. What happens then is that I the zoomWheel continues to be active in the mouse wheel.  

For reference, here's how we achieved the desired behavior this in cornerstoneTools v2:

```js
activate(element) {
  cornerstoneTools.pan.activate(element, 1);
  cornerstoneTools.stackScrollWheel.deactivate(element);
  cornerstoneTools.zoomWheel.activate(element);
}

deactivate(element) {
   cornerstoneTools.pan.deactivate(element, 1);
   cornerstoneTools.zoomWheel.deactivate(element);
   cornerstoneTools.stackScrollWheel.activate(element);
}
```

What is the appropriate API/approach to achieve this in V3? Is there a hook available from within this tool to tear down the tools that I activated when any other tool is activated? 

### Steps to Reproduce
N/A

**Expected behavior:**
N/A

**Actual behavior:** [What actually happened]
N/A

**Comment by dannyrb** [comment]
First and foremost, thanks for taking the time to create an issue and ask a detailed question. It's always great to see new faces commenting and contributing ^_^

### Why doesn't this tool already exist in `cornerstone-tools`

`cornerstone` + `cornerstone-tools` are meant to help developers create medical imaging viewers. Part of the reason we have the functionality as separate tools is because it makes them more composable and easier to use in a wider variety of ways. We'll often see `Viewer Implementations` create another layer on top of `cornerstone-tools` that manages which tools are active and when -- allowing for a single button to turn on/off `pan + zoom`, or have them as default active tools.

### Tool strategies

I *think* you're just looking for a shortcut to activate/deactivate two tools at once. Which could be done with a function instead of an entire custom tool; but if what you're looking for is a `zoom` that _also_ pans, it may be worth checking out tool strategies:

- [Zoom Tool Strategies](https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/tools/ZoomTool.js#L21-L25)

### Your original question

Tool classes can optionally implement methods that function as callbacks [for each mode change](https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/store/setToolMode.js#L259-L262). Examples being:

- `activeCallback`
- `passiveCallback`
- `enabledCallback`
- `disabledCallback`

It looks like you're correctly leveraging this, but again, if you're only using the tool to hold on/off methods, they should probably live outside of a tool.

If the callback doesn't fire when you're calling `setToolDisabled('your-tool-name')`, then it's possible you've encountered a bug. If when you examine all current tools: `cornerstoneTools.store.state.tools`, if the `modes` or `options` of each tool don't reflect what you'd expect, then there could be a bug. If they do match what you expect, but the active tool behavior doesn't align with their `modes` and `options`, then we could have an issue in our dispatchers.

I only say all of this because I don't think many developers are currently explicitly disabling tools or using these callbacks, so I want you to be aware of areas that may require a good report, example, and pull request to resolve. This is due partially to `v3` being new, and when you call `setToolActive` for an in-use mouse-binding, the previous tool is automatically set to passive.

**Comment by Ggpsv** [comment]
Thanks for the very thorough answer @dannyrb! 

>  think you're just looking for a shortcut to activate/deactivate two tools at once.

Yes, that's correct. I'll look into the `strategies` approach, that seems to be the most sensible one since you can configure for it.

> This is due partially to v3 being new, and when you call setToolActive for an in-use mouse-binding, the previous tool is automatically set to passive.

That's interesting. `passiveCallback` was not being called when I activated another tool while this tool was being used. Can you point out where "is automatically set to passive." happens in the codebase?

Thank you!

**Comment by dannyrb** [comment]
@Ggpsv, they're named "inputResolvers" which really just means that we try to resolve input conflicts when activating a new tool. You can find some of the logic here: https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/store/setToolMode.js#L312-L355

When we activate a tool, we...
1. Find tools with the same supported interaction types (mouse, touch, wheel, etc)
2. Find and call the appropriate `inputResolver` for that interaction type
    - This clears/removes options/settings that would be conflicting after the new tool is activated
3. Find tools that are active for the same element
4. Iterate over each active tool w/ the same supported interaction type
5. If all of their bindings/options were removed by the `inputResolver`, we call `setToolPassiveForElement` on them

https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/store/setToolMode.js#L352

**Comment by Ggpsv** [comment]
@dannyrb Thanks for the hint. This resolved my doubts regarding _where_ the source of the issue that I described. 

> Which could be done with a function instead of an entire custom tool (...)

As a last ask, can you give an example of the nature of the functions that you describe above? Where do these functions exist in the current design of `cornerstoneTools`?

**Comment by dannyrb** [comment]
> Where do these functions exist in the current design of cornerstoneTools?

I'm not sure I follow. Not everything has to take place in a tool. You can activate tools as part of your application's code. The OHIF Viewer, and it's extensions, are a practical example of this.

`cornerstone-tools` is not an application, it's a library that provides features/functionality to you may want to incorporate in your own application.

**Comment by Ggpsv** [comment]
Yeah I understand that now. That wasn't entirely clear 10 days ago. I'll be closing this issue now, thanks for all the feedback!
