### ISSUE TITLE
Converting data between other sources

### ISSUE THREAD

**Issue by b-wils** [cornerstonejs/cornerstoneTools#1119]
### Prerequisites

* [ ] Which version are you using? (Is it latest?)
cornerstone-core@2.3.0
cornerstone-math@0.1.8
cornerstone-tools@4.6.2
* [ ] Are you reporting to the correct repository?
* [ ] Did you search existing issues? (Were any related?)

### Description

Is there a recommended approach to convert measurements for usage with other systems?

For example we have an iOS app with it's own implementation of a RectangleROI tool. I want to persist those measurements (start/end coordiantes) from iOS to a database, fetch them on the web and have cornerstone render the same Rectangle. And Vice Versa.

One approach- Since I can inspect the tool state, I could manually rebuild by combining state from the database with defaults for any cornerstone specific fields that have not been saved. In reverse I can extract information from the specific object definition. This approach seems fragile since any changes to tool state may break this implementation.

Alternatively I could create a new RectangleROITool (unless there is a static/global one I can grab) and call createNewMeasurement and pass a mock event with specific data. This may be a good abstraction to create state, but there is no reverse method that could extract data.

**Comment by dannyrb** [comment]
👋 @b-wils 

> Is there a recommended approach to convert measurements for usage with other systems?

Recommended? Not really. It's up to the implementer to choose their mechanism/format for persistence, and ultimately, the mapping layer between that format and what CornerstoneTools uses.

> One approach- Since I can inspect the tool state

While not documented well, most tools have fairly spelled out toolState that can be examined by inspecting the code or source after creation. We've talked about formalizing this a bit more in a new major release where all tools have to conform to some standardized schema, and then instead of implementing a custom render function, we have a "renderer" that produces consistent output based on the input schema.

This allows tools to be more consistent with tool data, and for all tools to benefit from enhancements to a shared renderer.

This is not planned near future, but I agree that the level of control we currently allow tools makes things a bit more brittle and harder to reason out.

> This approach seems fragile since any changes to tool state may break this implementation.

It is fragile, but toolState should be seen as "Public API". Any breaking changes to it _should_ qualify a new major version. Cornerstone tools has been around for years, and we've had 4 major versions. I believe the bulk of which have not introduced breaking changes to toolState.

> Alternatively I could create a new RectangleROITool 

Only the Rectangle ROI Tool that's exposed as a top level export.

**Comment by b-wils** [comment]
Thanks @dannyrb ! This is exactly the type of info I was looking for guidance on.

> It is fragile, but toolState should be seen as "Public API". Any breaking changes to it should qualify a new major version. Cornerstone tools has been around for years, and we've had 4 major versions. I believe the bulk of which have not introduced breaking changes to toolState.

This especially was good to get confirmation on and give me confidence in this approach.
