### ISSUE TITLE
Eraser for scissors?

### ISSUE THREAD

**Issue by tommy-qichang** [cornerstonejs/cornerstoneTools#1159]
It seems the erasers couldn't apply to freehandscissors mask?
And I think the correctionscissors may not suitable for some case. For instance if I wanna delete a whole object, when I use correctionScissors it always fill the inside, but what I want is delete all of the inside part.....
Could you please advice how can I do this. Thanks.

**Comment by dannyrb** [comment]
You can use the `brush` tool with erase flag configured to always be on. This allows you to essentially create an "EraserBrush" tool. I've also witnessed several viewers creating behaviors like "double click erase".

Is there an example interaction you're trying to replicate? Is there a viewer that models it where you can pass on a video of that interaction and expected behavior?

**Comment by tommy-qichang** [comment]
I think eraserbrush is very easy to use. That's exactly what I want. 
I'm working a simple medical annotation system for machine learning users, and will open source once ready. Thank you so much for your help.

**Comment by LexaDel** [comment]
Hey guys!
How can I configurate flag for `brush` to create an "EraserBrush" tool?
I don't undestand how to setup `alwaysEraseOnClick` option.

Thanks!
