### ISSUE TITLE
Inconsistent area calculation between Freehand and comparable Rectangle ROI

### ISSUE THREAD

**Issue by dannyrb** [cornerstonejs/cornerstoneTools#1163]
RE: https://github.com/cornerstonejs/cornerstoneTools/pull/1161

Area calculation for Freehand ROI Tool produces different area result than Rectangle ROI Tool despite same point coordinates.

See linked pull request for example and discussion.

CC: @JamesAPetts

**Comment by zzfzfz** [comment]
I think I found the cause of the problem

Rectangle ROI use `utils/getPixelSpacing` to get `pixelSpacing` but Freehand ROI use the `image.columnPixelSpacing` and `image.rowPixelSpacing` directly.

I catch pixelSpacing data for both cases.
### Rectangle ROI 
use `utils/getPixelSpacing` get `0.78`
![image](https://user-images.githubusercontent.com/59550023/72048167-2490c600-32f7-11ea-98b4-a45c1eaec10c.png)

### Freehand ROI
use `image.columnPixelSpacing` get `0.8984375`
![image](https://user-images.githubusercontent.com/59550023/72048175-28244d00-32f7-11ea-8641-9ed52955072b.png)

Do we use `utils/getPixelSpacing` at `Freehand ROI` to get `PixelSpacing` instead of using image attributes directly?
@dannyrb @JamesAPetts

**Comment by JamesAPetts** [comment]
Interesting, thanks a lot for digging to the root of this issue!

So getPixelSpacing from utils checks the imagePlane first and then checks the image. I think when I originally made the freehand tool we must hav been checking on images where these values are the same, and I can't see any reason they wouldn't be normally.

@dannyrb , I think this is just because `netlify-example/metaDataProvider.js` has the wrong hardcoded pixel values for the demo metadataProvider.

I guess we should also make sure all tools use the helper?

**Comment by sbourouis** [comment]
I think this may fix the issue: https://github.com/cornerstonejs/cornerstoneTools/pull/1228
