### ISSUE TITLE
Can't run externals since update

### ISSUE THREAD

**Issue by aguai23** [cornerstonejs/cornerstoneTools#302]
Since I update to the latest commit today, I can't use cornerstonetools as normal. 
The error message is , 
TypeError: Cannot read property 'getEnabledElement' of undefined
    at getElementToolStateManager (app.js:10284)
    at Object.addStackStateManager (app.js:18531)
it seems that cornerstone can't be found, the problem may exist in externalModules.js,
let cornerstone = window.cornerstone;
let cornerstoneMath = window.cornerstoneMath;

can't find cornerstone, so how to fix this?

**Comment by dannyrb** [comment]
Are you using a packaged source or imports? What was your version before
you updated? Can you include a snippet of your setup code and maybe the
version number of each cornerstone library you are pulling in?

**Comment by aguai23** [comment]
The previous version I use is 0.9.1, but I made some change to the source code and build a package source myself. My code runs well before commit e3f788b98d23c2ac3cc26c5ecf7c4cb62cb04dda on Oct 18, since the commit "inject dependency", my code throw errors. 

import cornerstone from 'cornerstone-core';
import dicomParser from 'dicom-parser';
import cornerstoneTools from '../../library/cornerstoneTools';

this is my import part

**Comment by dannyrb** [comment]
If you're using the latest versions for these packages, you will notice
there was a major version bump. Major version bumps generally correlate
with breaking changes.

If one of the cornerstone libraries in your project have been upgraded to
1.0+, I recommend upgrading them all to latest: Cornerstone,
CornerstoneTools, and the image load libraries

And then use the npm/import specific instructions here:
https://tools.cornerstonejs.org/installation.html

If you have difficulty, or feel like the docs aren't clear enough, please
let me know and I can help you and update the docs to be a little clearer.

**Comment by aguai23** [comment]
I see your issue in cornerstone, and I tried to solve this error.
After I add this code, 
cornerstoneTools.external.cornerstone = cornerstone;
it runs well, but this may cause confusion to other developers if they don't notice this.

**Comment by dannyrb** [comment]
Unfortunately, I'm not the best person to answer this question. @swederik or @kofifus may be able to explain the change.

I believe we have slated more verbose errors for common setup problems like this -- Ideally, we want problems caused by major version changes to have easy/clear upgrade paths.

**Comment by swederik** [comment]
We needed to add a method to inject the cornerstone core version into tools (etc..) because some framework's build processes do not resolve duplicate dependencies properly. There were complaints of duplicate copies of cornerstone being loaded into applications because the WADO Image Loader depended on version 0.x.y and Tools depended on 0.x.z. With Meteor specifically, which we use in the OHIF Viewer, we had problems with this. I know some bundlers (e.g. webpack) would resolve the two versions safely, so this may not have been an issue for everyone.

For that reason, we decided to force the specification of the dependency packages and remove the NPM package dependencies themselves, and put them as dev dependencies.

It's not pretty, but it works. We put this information in the changelog and README, and made it during a major version update so it wouldn't break anyone's builds.

Sorry for the headache, but we are open to other ideas if you have any suggestions.

**Comment by aguai23** [comment]
ok, I see it in README. Seems that every import should contain a few more lines of code to solve the external problems, but I haven't thought of any better solutions yet. 
Thanks for your answer and patience.

**Comment by kofifus** [comment]
Hi swederik,

I have posted instructions for loading ES6 modules directly using latest Chrome in https://github.com/cornerstonejs/cornerstone/pull/191#event-1353847488

These can be incoreperated into the Wiki/Readme

They rely on 
  https://github.com/cornerstonejs/cornerstone/pull/191 
and
  https://github.com/cornerstonejs/cornerstoneWADOImageLoader/pull/144

But somehow the discussion of those PRs stopped

Is there any plans of merging them ? or anything I can do to advance this ?

Thanks!

**Comment by swederik** [comment]
I can't merge the WADO Image Loader issue until the tests run. I don't have any urge to set external to a default export on cornerstone core since I plan to drop the only dependency very shortly, so it would be wasted effort.

You can help get that WADO Image Loader ticket running properly. That would be great!
