### ISSUE TITLE
Allow input types to be enabled on elements that have not yet loaded/displayed an image

### ISSUE THREAD

**Issue by medihack** [cornerstonejs/cornerstoneTools#317]
In many examples the input sources are enabled straight after the element is enabled, e.g. [in the probe tool](https://github.com/cornerstonejs/cornerstoneTools/blob/master/examples/probe/index.html#L68). This throws an error when no image is displayed (or while it is loading) and the event is triggered on the element (e.g. the mouse cursor is moved there) as the input sources depend on an already loaded image, because of the `cornerstone.pageToPixel` function.

Two options:
- Change the examples to enable input sources after the image was loaded (to make this more clear when to enable those).
- Check in the event listeners if there is an attached image to the enabledElement and if not then just return.

I would prefer the second option. What do you think?

**Comment by dannyrb** [comment]
Thanks for creating an issue!

That example does need updated. In general, we recommend enabling input inside of a `.loadImage()` callback so you're guaranteed an image has been loaded. You can see this in the [all image tools example](https://github.com/cornerstonejs/cornerstoneTools/blob/master/examples/allImageTools/index.html#L145-L146).

I am also not a huge fan of this limitation. I think your second suggestion makes sense and is more elegant than the current implementation. I'll add it to our 2.1 milestone, unless @swederik thinks otherwise.

**Comment by swederik** [comment]
Agree with both of you, second option is good. Just merged the PR. Thanks!
