### ISSUE TITLE
Polygon-based segmentation idea

### ISSUE THREAD

**Issue by jpambrun** [cornerstonejs/cornerstoneTools#318]
I am playing with a new segmentation tool using polygons instead of pixels. It would require some effort to turn into a suitable PR and would add two dependencies [0,1]. Before going further, I wonder if it has any chance of being included?
[0] https://github.com/mourner/simplify-js/
[1] https://github.com/floorplanner/polygon-tools

It can draw nice and fast SVGs:
![multiple](https://user-images.githubusercontent.com/718384/34458419-015cb106-eda0-11e7-8372-db49b099e583.gif)

It can draw overlapping regions:
![overlap](https://user-images.githubusercontent.com/718384/34458420-0167d91e-eda0-11e7-96a6-6db836a2f877.gif)

It can split and join polygons:
![split_join](https://user-images.githubusercontent.com/718384/34458421-01727f2c-eda0-11e7-93df-f8a428532f54.gif)

It auto simplifies polygons which can be efficiently saved as a list of points:
![simplification](https://user-images.githubusercontent.com/718384/34458422-017c592a-eda0-11e7-8e70-f8f1cf52f1df.gif)

**Comment by dannyrb** [comment]
It's certainly up for discussion. _In general_, we try to avoid adding new dependencies, but for more advanced tools it would make sense that we'd want to lean on mature, permissively licensed packaged rather than reinventing the wheel.

Questions I have are:
- What is the _best_ way to include tools with additional external dependencies without forcing all `cornerstone-tools` consumers to incur the cost?
- What litmus test(s) do we employ to make sure we only allow new external dependencies for the "right" tools?
- If we take the approach of making it easier to "plugin" your own tools, how do we maintain/curate/surface 3rd party tools? What tools should be core tools? (Lots of other questions in this realm)

Regardless, I like your tool/implementation. I think we can include it in some capacity, but we'll likely need to answer a few larger direction/architecture questions before we can determine the best way to include it. 

If you have any thoughts @jpambrun, please feel free to chime in. I'll "claim" this issue for now, because I feel it's important we get a solid answer to it sooner rather than later.

CC: @swederik

**Comment by jpambrun** [comment]
One option would be to create a cornerstoneTools-extras package where external deps are allowed. 

The current approach of copying code in cornerstoneMath is not ideal either IMO.

**Comment by dannyrb** [comment]
@jpambrun dropping in to let you know I haven't forgotten about this issue. Still working through some Holiday scheduling issues to discuss this ;)

We're having a larger community meeting to establish working groups for roadmap, documentation, etc. Once that's done, we should be able to come to conclusions more quickly for issues like this.

**Comment by jpambrun** [comment]
Don't worry, I am also quite busy and I understand these things take time.

In addition, I realize I am proposing to take 2 new dependencies while the current total is 0 (beside cornerstoneMath).

**Comment by dannyrb** [comment]
We _do_ try to limit dependencies, but I don't see any harm in providing a framework for 3rd party tools/plugins that have dependencies for advanced functionality. The bigger question is how best to make this possible without `CornerstoneTools` directly gaining those dependencies.

Ideally, we'd create a new way to "register" custom tools/plugins. IE.

```
import polygonROI from '3rd-party-package'

cornerstoneTools.register(polygonROI, {
    mouseToolName: 'polygonROI',
    touchToolName: 'polygonROITouch'
})
```

But that brings into question:
- What tools should we continue to maintain, and which ones should be turned into external tools?
- What "base" tools can we provide to make it easier for tool authors to create their own?
- What API considerations do we need to take into account to make external plugin management a breeze?
- How do we curate, assist with, and promote 3rd party tool development?
- Other important stuff I'm forgetting

I realize I'm mostly rehashing stuff I've already said, but please feel free to offer thoughts @jpambrun and @swederik. Still aiming to have an answer to this question before the end of the month.

**Comment by dannyrb** [comment]
@jpambrun, do you have a repository for this? We're in the middle of a large refactor that makes it much easier to add 3rd party tools. I'd love to use what you have as an example of how to add an advanced tool.

**Comment by jpambrun** [comment]
It's not public yet since at the time I just felt it was a bit too hacky (also didn't have time to touch it since..). I'll try to clean it up a bit and make it available this week end.

**Comment by jpambrun** [comment]
gh://jpambrun/cornerstonePenBrushExperiment

I had to split it from a bunch of other experiment, but I didn't have time to clean it up yet.  

I also hacked in smoother touch gestures and pen support.. but none of this is anywhere ready for prime time..

It looks like this now:
https://random.jfpb.net/7724d6e33c7023bb_2018-08-18-14-17-22.mp4

**Comment by dannyrb** [comment]
I'm going to close this issue. I think this is a great 3rd party tool idea, but it doesn't need to remain active/open. I've created a new tag to find interesting thought pieces like this, even when they're closed, a little bit easier.

This may be something that I port myself this year, but no promises. I have my sights set on MPR + VTK.js first. If anyone else does make the effort, please be sure to reach out! As we build our list of maintained 3rd party tools, this would be a nice one to add to the list.
