### ISSUE TITLE
Change handles style

### ISSUE THREAD

**Issue by Lemenxzy** [cornerstonejs/cornerstoneTools#330]
hi :
  I want to chenge handles style when I use ellipticalRoi Tools  , I don't know what to do now,can you help me please，thanks.

**Comment by dannyrb** [comment]
@Lemenxzy I _think_ most of the handle style changes are global, and not per tool, but I'd need to double check. What characteristics are you trying to change?

**Comment by Lemenxzy** [comment]
I trying to change handles size or let their hide . Because the elliptical is very small , the handles hid the elliptical from view .

**Comment by dannyrb** [comment]
Please keep in mind that a handle may look large in comparison to a ROI, but as you zoom in, the handles should stay the same size while the ROI gets larger. The handles exist to create a point where you can interact with and transform the tool's data with mouse or touch input.

If you're sure changing the handle size is the right solution, you can see that we have the following related topics open:

- Issue: https://github.com/cornerstonejs/cornerstoneTools/issues/252
- PR (proof of concept): https://github.com/cornerstonejs/cornerstoneTools/pull/262

Which means that this change is possible, but you'll likely either need to pull and modify the source yourself, or create a pull request with the proposed API change for your tool and wait for it to be merged in order to achieve the behavior you want.

**Comment by dannyrb** [comment]
I'm going to close this issue as its a duplicate of #252. I do believe we'll see this addressed shortly after a `v3` release.
