### ISSUE TITLE
Restore tool state

### ISSUE THREAD

**Issue by tlacaelelrl** [cornerstonejs/cornerstoneTools#409]
cornerstone-core - 2.0.0
cornerstone-tools - 2.0.0

Hello.

I am trying to reuse one of the tools for a different purpose so I am unsure if this is possible or if I would have to write a new tool.

The tool in question is the rectangleRoi

The basic idea is to draw a rectangle based on coordinates with the end result being able to highlight for instance the thorax, we already know based on pixel coordinates where the thorax is but can't draw it as that would require someone interfacing with the mouse.

One of the ideas that came up was getting how the rectangleRoi saves the tool state which we were able to do by cornerstoneTools.getToolState(element, "rectangleRoi");

```javascript
cornerstoneTools.getToolState(element, "rectangleRoi");
```
which returns something like the following

```json
{
	"data": [{
		"visible": true,
		"active": false,
		"invalidated": false,
		"handles": {
			"start": {
				"x": 882.0269058295971,
				"y": 1500.6502242152467,
				"highlight": true,
				"active": false
			},
			"end": {
				"x": 2353.6322869955156,
				"y": 2430.085201793722,
				"highlight": true,
				"active": false
			},
			"textBox": {
				"active": false,
				"hasMoved": false,
				"movesIndependently": false,
				"drawnIndependently": true,
				"allowedOutsideImage": true,
				"hasBoundingBox": true,
				"x": 2353.6322869955156,
				"y": 1965.3677130044844,
				"boundingBox": {
					"width": 178,
					"height": 25,
					"left": 791.5695067264573,
					"top": 104.93049327354261
				}
			}
		},
		"area": 1367761.5144483089
	}]
}
```

Then based on the know coordinates of the thorax we could build that object but before doing so we need to know if we will actually be able to use it.

So assuming that we were able to build that same object with the above given properties, is there something like this?

```javascript
cornerstoneTools.setToolState(element, "rectangleRoi", data);
```

where data equals to the json posted above?

I tried finding it and thought that cornerstoneTools.addToolState would do it but it does not

**Comment by pieper** [comment]
Hi - 

I've been working on saving and restoring tools to DICOM structured reports so I have some code here that shows how to create a tool state (length tool in this case) and populate it into the cornerstoneTools tool state manager:

https://github.com/OHIF/Viewers/blob/40ae48238b431477787152e1dc6dc92262ce1b58/Packages/ohif-viewerbase/client/lib/handleSR.js#L11-L34

Key call is restoreToolState.

HTH,
Steve

**Comment by henryhe1** [comment]
@pieper has anyone done this with the Freehand tool? Also is there any documentation for the JSON format of the tool states? Where is the bounding box and area/stdev calculated? 

I'm working on a mat file to JSON converter so that I can load segmentation. Eventually want to save into the DICOM

**Comment by pieper** [comment]
Hi @henryhe1  - we haven't yet done the freehand tool but it's on the todo list.  We are working with a group to finalize the form of the DICOM SR that will store the various measurement tools and it should be in place by the end of the summer.

Right now there's no json format for the toolstate AFAIK, but maybe @JamesAPetts is using something for his connection to XNAT.

Are your mat files outlines or labelmaps?  If outlines then the SR makes sense.  If they are labelmaps you should consider making DICOM SEG objects.  See [DCMQI](https://github.com/QIICR/dcmqi) and the [DICOM4QI](https://qiicr.gitbooks.io/dicom4qi/content/) connectathon for more info and pointers to tools.

**Comment by JamesAPetts** [comment]
@pieper , @henryhe1, In XNAT I'm currently reading from AIM imageAnnotationCollection/DICOM-RT and writing to AIM imageAnnotationCollection. The toolData itself is a POJO, which I construct from the file and add to the toolState. The freehand toolData has circular references to make it easier to manipulate, which is why there I don't use a json schema. This could always be worked around though. You can see the POJO structure by drawing an ROI and just writing out the element's toolData, its relatively straightforward.

As @pieper  says, if your objects are more like masks, we'll have a more stable/useful brush tool in cornerstoneTools v3 which will be better suited than the freehand tool to hold this kind of data.

**Comment by henryhe1** [comment]
Hey @pieper @JamesAPetts thanks for the quick replies. The mat files are outlines (x and y coordinates), so I was thinking of storing them as DICOM SR. Any tips on how to do this to create a quick demo (read and write)? 

And I only mention JSON because that's what the format of the toolData the cornerstoneTools freehand example webpage returned - is that version outdated? I definitely don't need to use json if there's a better way. And forgive me but what is XNAT, AIM, and POJO? 

Thanks

**Comment by pieper** [comment]
Storing in dicom SR a big topic - if you want something quick just use json with an ad hoc schema that suits your needs and ignore the standard and don't worry about anybody else using your data.

But if you want to help us make standards based interoperable DICOM SR objects that would be great.  See the links above to learn more about it (there are lots of reasons scientific and engineering reasons why it's important).  We aspire to have all the cornerstone tool types save and restore in OHIFViewer by RSNA (late November)

**Comment by dannyrb** [comment]
I think the heart of this question has been answered. Improving tool state export/import will likely become more and more of a priority, but we can tackle that in a different issue.

Thanks for all of your thoughts and help on this issue everyone!

@all-contributors please add @pieper for Answering Questions
