### ISSUE TITLE
Exporting and Restoring ToolState; Handling Measurement Updated Events

### ISSUE THREAD

**Issue by piyush-goel19** [cornerstonejs/cornerstoneTools#482]
Hi dannyrb,

I'd like to acknowledge the work you are doing here and I must say cornerstone is a great library. It has certainly helped a lot. I have been using this for quite a some time now. Now I have started working in it i.e I'm now considering developing my custom tool something like ellipticalRoi. I have read your material on the same via https://github.com/cornerstonejs/cornerstoneTools/wiki. From that I'm able to understand what we need to do in order to create custom tool like listen the ImageRendered event n all but not fully. Can you plz help me understand the flow of control of ellipticalRoi tool(specifically) breifly right from the statement "cornerstoneTools.ellipticalRoi.activate(element,1)" ?? 
I'm using cornerstone-tools - 2.0.0 - 2017-12-13 version library.

Also,
I want to call a function(of my own) immediately **only** after user has finished drawing ellipse(after every single draw). I'm having some difficulties with the mouseEvents like I have called that function inside onImageRendered(e) function, so its being called twice(one at start handle and other at end handle), but i want to call function only after end handle i.e when user has finished drawing. Can anyone help??

Any help would be appreciated...

Thank you

**Comment by gillib** [comment]
I also need an event that will fire when an roi was finished drawing. with the toolType, and the new roi data in that event.
did you figure out where would be the right place to add such an event?

**Comment by dannyrb** [comment]
Thanks for the shout-out! FWIW, only a very small percentage of the code in this repository was actually contributed by me. We're lucky to have an active and generous community that helps shape and grow the library (:

I'd be curious to hear what you're trying to trigger after the tool has been placed. There might be an easier approach given the current setup. It may be worth adding an event that triggers when multi-step tools have been placed, but it sounds like you need the event to fire when the annotation has been moved/resized as well?

The current documentation is not great at laying out how to create your own tool. In part, because it's not overly easy to without forking this repository and rebuilding the source. We have put some effort into a new major release that changes the API so tools function more like plugins. When that release lands, it will include a much better/simpler guide on how to create and add your own custom tools, as well as extend existing ones.

vNext Branch: https://github.com/cornerstonejs/cornerstoneTools/tree/vNext?files=1
vNext Project: https://github.com/cornerstonejs/cornerstoneTools/projects

**Comment by piyush-goel19** [comment]
Hi dannyrb

Thanks for replying. As per ur request I'd like to clarify more upon what I need.

Replying to "I'd be curious to hear what you're trying to trigger after the tool has been placed. There might be an easier approach given the current setup. It may be worth adding an event that triggers when multi-step tools have been placed, but it sounds like you need the event to fire when the annotation has been moved/resized as well?". 
Basically I want to collect all the measurements of the ROI like left,top,width n height etc and send it to server only upon the completion of the multi-step tool like ellipse(inside my own function).
And yes I need to call such function or trigger event even when measurements are changed as a result of tool/drawing move/resize.


And I have one more query regarding ROI and that's "can I have ROI/annotations drawn on my canvas without the use of mouse totally i.e you have all the coordinates of the ROI and you just want ROI to be drawn as per those coordinates/measurements and at the same time save that annotation to that canvas/image only."

**Comment by dannyrb** [comment]
@gillib's PR #501 appears to address your first issue. We can continue conversation there of an ideal implementation.

You can export and restore state for any cornerstone tool. So you could generate, without the use of a mouse, state that represents and ROI and "restore" it to achieve the desired behavior.

On my phone, so here are some notes for me:
- Link export/restore state api info
- add documentation tag and to documentation project
- follow up on PR
