### ISSUE TITLE
Crosshairs tool only works for one element

### ISSUE THREAD

**Issue by catalinaduplat** [cornerstonejs/cornerstoneTools#642]
### Prerequisites

* [X] Are you running the latest version?
* [ ] Are you reporting to the correct repository?
* [ ] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

### Description
If you activate crosshairs, it only works for the first element you use it with, if you try to use it then in other enabled elements (which have the tool active) it doesn't work. 

**Expected behavior:** [What you expected to happen]
It should work with all enabled elements that have the tool activated.

**Comment by dannyrb** [comment]
@catalinaduplat, can you provide a reproduction for this issue? I know my company has a working Crosshairs tool, but I believe we use a custom synchronizer because we needed different behavior. If this is for sure not working, I can take a peak and see what the key differences are and at least provide some guidance on a fix.

**Comment by catalinaduplat** [comment]
Let me first check if with the released version this issue is still there. Thanks!

**Comment by dannyrb** [comment]
This has been open for a long time with no reproduction. I am more than happy to re-open this issue if a reproduction is provided.
