### ISSUE TITLE
Live examples not working

### ISSUE THREAD

**Issue by vdnsnkv** [cornerstonejs/cornerstoneTools#690]
Live examples stopped working recently.

For instance,  [annotation example](https://rawgit.com/cornerstonejs/cornerstoneTools/master/examples/annotation/index.html) does not react to any button click.

There are two errors in the console.

> Refused to execute script from 'https://rawgit.com/cornerstonejs/cornerstoneTools/master/dist/cornerstoneTools.js' because its MIME type ('') is not executable, and strict MIME type checking is enabled.

and 

> Uncaught (in promise) TypeError: Cannot read property 'IMAGE_RENDERED' of undefined
    at Object.activate (mouseButtonTool.js:269)
    at index.html:233

**Comment by dannyrb** [comment]
That's odd. I could have sworn we updated scripts to pull the latest versions from a CDN. The issue is likely related to this:

https://stackoverflow.com/questions/17341122/link-and-execute-external-javascript-file-hosted-on-github

**Comment by Zaid-Safadi** [comment]
This is caused by the version of cornerstone shipped in the examples being older. I fixed this locally by referencing the latest version from unpkg instead of the local:
`<script src="https://unpkg.com/cornerstone-core/dist/cornerstone.js"></script>`

I can go ahead an update all the examples to always reference the latest cornerstone as above unless there is a reason it is preferred to ship it along with the examples, then I'll just update that.

**Comment by dannyrb** [comment]
Thanks for the fix, @Zaid-Safadi 🎉 
If anyone is still having issues, please feel free to continue the conversation here or create a new issue.
