### ISSUE TITLE
What is the plan for vNext?

### ISSUE THREAD

**Issue by wwwillchen** [cornerstonejs/cornerstoneTools#713]
Hello -

I've been using cornerstone tools v2 for a while now and I noticed that the core team has been working on v3 (i.e. vNext branch) and I read through some of the issues and commits, but still have a couple of a high-level questions.

My impression is that v3 is primarily about refactoring / creating a plugin architecture / etc and not so much about new functionality. Is that correct?

Because it's a new major version, I'm assuming there's breaking changes in the API. Do you have an estimate of how significant the breaking changes will be? For example, if we have custom cornerstone tools, I'm assuming we'll need to rewrite all of them. Aside from custom tools, will regular usage of cornerstone tools have many changes in the API (e.g. different types of events emitted)?

Also, just wanted to say thanks for all the great work on cornerstone.

-Will

**Comment by dannyrb** [comment]
@wwwillchen, I actually have a _draft_ of a "Release Candidate" announcement I intend to polish up and publish that addresses the bulk of these questions. Here are a few high level answers. We can dig into specifics if the Release Candidate announcement doesn't cover information you're looking for:

> My impression is that v3 is primarily about refactoring / creating a plugin architecture / etc and not so much about new functionality. Is that correct?

Yes, it is primarily a refactor. It's goal is to make extending/adding functionality easier without requiring a fork and rebuild. We have also started down the path of shoring up inconsistencies across tools, 

> Do you have an estimate of how significant the breaking changes will be?

The changes aren't too drastic. We:

- Shrank "Top Level" exports to only expose functionality most users will need for common implementation (think tools, `setToolActive`, `getToolState`, synchronizers, `EVENTS`, etc).
- Pulled out the more granular/internal methods and exposed them via `import`/`register` (`manipulators`, `drawing`, etc.). 

This is mostly to make life easier for tool authors, and to allow for registering and sharing functionality across different tools. Most old methods still exist. You may need to update where you're pulling them from.

Other than that, how you change the `state` of a tool (now `mode`) has been simplified. Instead of every tool having an `activate` method, there is a top level `setToolActive` method. Tools can implement a callback if they wish for custom code to execute when they are activated (this is a common pattern in this refactor).

There are a few other abstractions you can now leverage to simplify the logic of any "tool manager" you may have created. The library now tracks tool state across `enabledElements`, does some magic to determine which tool should handle events raised by `cornerstone-core`, and paves the way for some advanced features that would have been difficult/impossible in v2; however, most of these shouldn't require changes.

>  If we have custom cornerstone tools, I'm assuming we'll need to rewrite all of them.

Maybe? v2 tools are an odd breed. Most were activated by adding event listeners, and then deactivated by removing those event listeners. No events were removed, and most internal methods are still exposed in some way, so tools built in this manner could still work.

The issue you'll run into is the same limitation all v2 tools had. They were "dumb", or unaware of other tools. Converting a v2 tool to v3 nets you some benefits, and shouldn't take much time. If you need help, let me know! My team just wrapped up converting 8 or tools. Each one took 30 to 60 minutes to convert.

> Aside from custom tools, will regular usage of cornerstone tools have many changes in the API (e.g. different types of events emitted)?

It shouldn't feel too different. We had to keep the scope small because we are a very small group of infrequent volunteers. I don't think a single event was added or removed? (Other than some of the events in the ENUM that were actually `cornerstone-core` events). The hope is that this simplifies a lot of existing implementations and opens the door for more advanced features and easier maintainability.

**Comment by wwwillchen** [comment]
OK thanks for your detailed response. I'm guessing you'll announce on https://groups.google.com/forum/#!forum/cornerstone-platform?

Look forward to your RC.

**Comment by dannyrb** [comment]
@wwwillchen, I don't frequent the forum as often as I should. I'm ashamed to admit it, but the look and feel of it scares me away :P 

I will make sure to cross-post any announcements made in this repository to that forum -- I appreciate the reminder.
