### ISSUE TITLE
Use ImagerPixelSpacing when PixelSpacing is missing

### ISSUE THREAD

**Issue by kofifus** [cornerstonejs/cornerstoneTools#806]
Some modalities do not populate PixelSpacing (x00280030) in which case tools such as length show 'pixels' instead of 'mm'

In these cases is may be better to (instead of showing pixels) use ImagerPixelSpacing ('x00181164') if available.

We do that in our application however some may not desire that so maybe it should be configurable ?

See further info on those tags here - http://gdcm.sourceforge.net/wiki/index.php/Imager_Pixel_Spacing under "ImagerPixelSpacing to PixelSpacing"

**Comment by kofifus** [comment]
FYI what we're doing here is:

```
if (!dataSet.elements['x00280030']) dataSet.elements['x00280030'] = dataSet.elements['x00181164'];
```

**Comment by dannyrb** [comment]
It's an interesting problem. There are a decent number of tags that can influence how measurements are interpreted. We touched on it a bit in an [ultrasound issue a while back](https://github.com/cornerstonejs/cornerstoneTools/issues/684#issuecomment-435048421).

The viewer I work in has a custom `metaDataProvider` that will set pixelSpacing to the "highest priority" tag. Ultrasound specific tools use metadata from Ultrasound region tag(s).

Arguably, that's not the best place for the logic to live. We chose it because it's the _easiest_ location to update and have all tools utilize the correct value. I'd be interested in hearing other arguments, now that we're in a better place to revise tool implementations.

**Comment by kofifus** [comment]
We actually really need US regions as well ! 

As I understand it you can't just use the values there - they are only relevant within a particular region .. if an US has multiple regions, different annotations (ie lengths) will have different values in mm in the different regions even if they have the same value in pixels.

Ideally also you want to show the regions so that a user does not create an annotation that crosses regions (and if he does show it in pixels).

But all that is a bit off topic to this issue which is specific to ImagerPixelSpacing and PixelSpacing ..

Perhaps you can ask the other core maintainers if they are ok with using ImagerPixelSpacing when PixelSpacing is missing by default ?

**Comment by swederik** [comment]
Yeah based on the link that @kofifus posted, it seems that falling back from PixelSpacing to ImagerPixelSpacing is fine. We should put that link in the code comments or something though. We also have to be sure that we aren't displaying `mm` if no values are present. If we don't know anything, we can't default to 1x1, we have to display things in `pixels` for safety.

Thanks @kofifus for pushing this forward. US regions would be great but that's a significant effort to add. We would have to update pageToPixel etc.

**Comment by swederik** [comment]
Good question.... 

In my mind the metadata providers should just faithfully return the metadata, and the consumers should implement any logic like this.

Since I _believe_ it makes sense to also set the cornerstone `image`'s `rowPixelSpacing` and `colPixelSpacing` using this same logic (someone please correct me if I am wrong, would ImagerPixelSpacing ever break the way things are displayed?). In that case, what we could do is implement this logic in a function inside `createImage`, somewhere prior to this line:

https://github.com/cornerstonejs/cornerstoneWADOImageLoader/blob/master/src/imageLoader/createImage.js#L120

Currently, it just uses what is in imagePlaneMetadata. Instead, it would check imagePlaneMetadata for a value, and if it's not present, check for ImagerPixelSpacing via the metaDataProvider, and if that is also empty, use null.

**Comment by dannyrb** [comment]
Merged: https://github.com/cornerstonejs/cornerstoneWADOImageLoader/pull/261

Will be available in the next release 👍

**Comment by dannyrb** [comment]
Updating to indicate we reverted this behavior, and why: https://github.com/cornerstonejs/cornerstoneWADOImageLoader/pull/261#issuecomment-499951878
