### ISSUE TITLE
_getEnabledElement returns undefined

### ISSUE THREAD

**Issue by d13g0** [cornerstonejs/cornerstoneTools#938]
I am currently working on a project that involves the cornerstone libraries (react-cornerstone-viewport 0.1.27 and cornerstone-tools 3.9.2).

I have one CornestoneViewport and one brush tool. I can change the segmentation (previous, next); change the brush size; but if I try to hide the segmentations using:
** `hideAllSegmentationsOnElement` **

It is giving me this error:

```
cornerstone.js:2388 Uncaught Error: getEnabledElement: parameter element must not be undefined
    at Object.getEnabledElement (cornerstone.js:2388)
    at BaseBrushTool._getEnabledElement (cornerstoneTools.js:25163)
    at <anonymous>:1:30
```

so it seems that the element (this.element) is not set in the brush tool.

This is what I am kind of doing in my React component (render method) just for testing:

```
cornerstoneTools.addTool(this.state.brushTool)
return (
<div>
<CornerstoneViewport ...
    cornerstoneTools = {cornerstoneTools}
   ... />
</div>
)
```

Do you have an idea of what I need to do here? 

I would appreciate any help, Thanks.

**Comment by dannyrb** [comment]
CC: @JamesAPetts

**Comment by JamesAPetts** [comment]
Hey, I'll try and reproduce this later today on my system. I'm currently using the `hideSegmentationOnElement` functionality in production, but not the hide all. I'll get back to you soon :).

**Comment by JamesAPetts** [comment]
Hey, got a quick chance so checked this now. `this.element` is defined for me, and thus `hideAllSegmentationsOnElement` works correctly.

`this.element` for any tool is set when you call `addToolForEnabledElement` or `addTool` ([See here](https://github.com/cornerstonejs/cornerstoneTools/blob/c5eb105d449a6ea3c3f8c37ad3e4cdd20d918808/src/store/addTool.js#L32)). So that's a good place to start.

If you pull down the cornerstoneTools library, you can see a minimum working example by hosting a static site at your `cornerstoneTools` directory with e.g.:
`python -m SimpleHTTPServer 8888`

and `npm run dev` to build the lib, this will also track changes you make so you can play around.

An example with a button hooked up to `hideAllSegmentationsOnElement` can then be found at:

`http://localhost:8888/netlify-example/brush/`

If you can give a minimum working example of your use case I'd be happy to have a look at it.

Cheers,
James

**Comment by swederik** [comment]
@d13g0 Are you still having this issue after our changes? I think it was related to passing `cornerstoneTools = {cornerstoneTools}` into the component (which was previously necessary, but is no longer required). I'm guessing we can close this.

**Comment by dannyrb** [comment]
Closing for now. Please feel free to continue the conversation if your issue is not resolved.
